trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  kubernetesServiceConnection: Superset-DEV-uni-apps-aks-dev-ictd-oi-superset-dev-1684231822360
  kubernetesNamespace: ictd-oi-superset-dev

steps:
- task: HelmDeploy@0
  displayName: 'Add Superset Helm Repo'
  enabled: true
  inputs:
    connectionType: Kubernetes Service Connection
    kubernetesServiceEndpoint: $(kubernetesServiceConnection)
    command: 'repo'
    arguments: 'add superset https://apache.github.io/superset'
    namespace: $(kubernetesNamespace)

- task: HelmDeploy@0
  displayName: Helm deploy Superset
  inputs:
    connectionType: Kubernetes Service Connection
    kubernetesServiceEndpoint: $(kubernetesServiceConnection)
    command: upgrade
    chartType: Name
    chartName: superset/superset
    releaseName: superset
    valueFile: helm/values.yaml
    namespace: $(kubernetesNamespace)

- task: Kubernetes@1
  displayName: Set up Ingress
  inputs:
    connectionType: Kubernetes Service Connection
    kubernetesServiceEndpoint: $(kubernetesServiceConnection)
    command: apply
    arguments: '-f azure/ingress.yaml'
    namespace: $(kubernetesNamespace)
