trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  kubernetesServiceConnection: Superset-DEV-uni-apps-aks-dev-ictd-oi-superset-dev-1684231822360
  kubernetesNamespace: ictd-oi-superset-dev

steps:
- task: HelmDeploy@0
  displayName: 'Delete Superset Helm'
  inputs:
    connectionType: Kubernetes Service Connection
    kubernetesServiceEndpoint: $(kubernetesServiceConnection)
    command: 'uninstall'
    arguments: 'superset'
    namespace: $(kubernetesNamespace)

- task: Kubernetes@1
  displayName: Delete PVC in namespace
  continueOnError: true
  inputs:
    connectionType: 'Kubernetes Service Connection'
    kubernetesServiceEndpoint: $(kubernetesServiceConnection)
    command: delete
    arguments: "pvc --all"
    namespace: $(kubernetesNamespace)
