apiVersion: v1
kind: Secret
metadata:
  name: giga-superset-secrets
  namespace: giga-superset
type: Opaque
stringData:
  POSTGRESQL_USERNAME: "giga-superset"
  POSTGRESQL_PASSWORD: "giga-superset"
  POSTGRESQL_DATABASE: "giga-superset"
  SECRET_KEY: ""
  SLACK_API_TOKEN: ""
  INGRESS_HOST: ""
  GOOGLE_CLIENT_ID: ""
  GOOGLE_CLIENT_SECRET: ""
  AZURE_CLIENT_ID: ""
  AZURE_CLIENT_SECRET: ""
  AZURE_TENANT_ID: ""
  DEPLOY_ENV: ""
MAPBOX_API_KEY: ""