jobs:
  - deployment: Deploy
    displayName: Build and push Superset
    environment: $(kubernetesEnvironment)
    strategy:
      runOnce:
        deploy:
          steps:
            - checkout: self

            - task: Docker@2
              displayName: Login to container Registry
              inputs:
                command: login
                containerRegistry: $(ACR_SERVICE_CONNECTION)

            - task: Docker@2
              displayName: Build and push Superset image to container registry
              inputs:
                command: buildAndPush
                repository: giga-superset
                containerRegistry: $(ACR_SERVICE_CONNECTION)
                tags: |
                  $(Build.SourceVersion)
