jobs:
  - deployment: Deploy
    displayName: Create/update K8s configuration resources
    environment: $(kubernetesEnvironment)
    strategy:
      runOnce:
        deploy:
          steps:
            - checkout: self

            - task: Kubernetes@1
              displayName: Create Superset secrets
              inputs:
                namespace: $(kubernetesNamespace)
                configurationType: inline
                command: apply
                useConfigurationFile: true
                inline: |
                  apiVersion: v1
                  kind: Secret
                  metadata:
                    name: "giga-superset-secrets-$(deployEnv)"
                    labels:
                      app.kubernetes.io/name: giga-superset
                      app.kubernetes.io/part-of: giga-dataops-platform
                      app.kubernetes.io/component: superset
                  stringData:
                      POSTGRESQL_USERNAME: "$(postgresqlUsername)"
                      POSTGRESQL_PASSWORD: "$(postgresqlPassword)"
                      SECRET_KEY: "$(secretKey)"
                      GOOGLE_KEY: "$(googleKey)"
                      GOOGLE_SECRET: "$(googleSecret)"
                      AZURE_TENANT_ID: "$(azureTenantID)"
                      DEPLOY_ENV: "$(deployEnv)"
